[phases.setup]
nixPkgs = ['nodejs_18', 'npm-9_x']

[phases.install]
cmds = ['npm install --prefer-offline=false --no-audit --no-fund']

[phases.build]
cmds = ['npm run build']

[start]
cmd = 'node packages/affinity-groups/dist/index.js'