[phases.setup]
nixPkgs = ['nodejs_18', 'npm-9_x']

[phases.install]
cmds = ['npm cache clean --force', 'npm install --no-cache']

[phases.build]
cmds = ['npm run build']

[start]
cmd = 'node packages/affinity-groups/dist/index.js'