// Real allocations org-vocab subset (collision families + acronym targets),
// captured from current-projects.json?filters=1 for resolver tests.
export const orgsSample: string[] = [
  "California Department of Water Resources",
  "California Institute of Technology",
  "California Office of Environmental Health Hazard Assessment",
  "California Polytechnic State University, San Luis Obispo",
  "California State Polytechnic University, Humboldt",
  "California State Polytechnic University, Pomona",
  "California State University East Bay",
  "California State University-Bakersfield",
  "California State University-Channel Islands",
  "California State University-Chico",
  "California State University-Fresno",
  "California State University-Fullerton",
  "California State University-Long Beach",
  "California State University-Los Angeles",
  "California State University-Monterey Bay",
  "California State University-Northridge",
  "California State University-Sacramento",
  "California State University-San Bernardino",
  "California State University-San Marcos",
  "Carnegie Mellon University",
  "East Texas A&M University",
  "Eastern Illinois University",
  "Eastern Washington University",
  "George Washington University",
  "Georgia Institute of Technology",
  "Illinois Institute of Technology",
  "Illinois State University",
  "Indiana University-Purdue University Fort Wayne",
  "Massachusetts Institute of Technology",
  "Miami University",
  "Northern California Institute for Research and Education, Inc.",
  "Purdue University",
  "Purdue University in Indianapolis",
  "SUNY - Farmingdale State College",
  "SUNY College at Brockport",
  "SUNY College at Buffalo",
  "SUNY College at New Paltz",
  "SUNY College at Oswego",
  "SUNY Downstate Health Sciences University",
  "SUNY Health Science Center at Syracuse",
  "SUNY at Albany",
  "SUNY at Binghamton",
  "SUNY at Buffalo",
  "SUNY at Stony Brook",
  "Southern Illinois University, Carbondale",
  "Stanford University",
  "Stanford University School of Medicine",
  "Texas A&M AgriLife Research",
  "Texas A&M International University",
  "Texas A&M University",
  "Texas A&M University at Galveston",
  "Texas A&M University, Kingsville",
  "Texas A&M University-San Antonio",
  "Texas A&M University\u2013Texarkana",
  "Texas Advanced Computing Center",
  "Texas Christian University",
  "Texas State University",
  "Texas Tech University",
  "University of California, Berkeley",
  "University of California, Davis",
  "University of California, Irvine",
  "University of California, Los Angeles",
  "University of California, Merced",
  "University of California, Riverside",
  "University of California, San Diego",
  "University of California, San Francisco",
  "University of California, Santa Barbara",
  "University of California, Santa Cruz",
  "University of Illinois at Chicago",
  "University of Illinois at Springfield",
  "University of Illinois at Urbana-Champaign",
  "University of Mary Washington",
  "University of Miami",
  "University of North Texas",
  "University of Southern California",
  "University of Texas Health Science Center at Houston",
  "University of Texas Health Science Center at San Antonio",
  "University of Texas MD Anderson Cancer Center",
  "University of Texas Medical Branch at Galveston",
  "University of Texas Rio Grande Valley",
  "University of Texas Southwestern Medical Center",
  "University of Texas at Arlington",
  "University of Texas at Austin",
  "University of Texas at Dallas",
  "University of Texas at El Paso",
  "University of Texas at San Antonio",
  "University of Texas of the Permian Basin",
  "University of Washington",
  "University of Washington Bothell",
  "Washington State University",
  "Washington University School of Medicine",
  "Washington University in St. Louis",
  "Washington and Lee University",
  "West Texas A&M University",
  "Western Illinois University",
  "Western Washington University"
];
