[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "xdmod-python"
version = "0.1.0"
description = "Python MCP server for XDMoD data analytics using the official data analytics framework"
authors = [
    {name = "ACCESS-MCP", email = "noreply@access-ci.org"}
]
dependencies = [
    "mcp>=0.9.0",
    "pandas>=2.0.0",
    "requests>=2.31.0",
    "numpy>=1.24.0",
    # Will add XDMoD data analytics framework when we identify it
]

[project.optional-dependencies]
dev = [
    "pytest>=7.0.0",
    "mypy>=1.0.0",
    "black>=23.0.0",
]

[tool.setuptools.packages.find]
where = ["src"]

[project.scripts]
xdmod-python = "xdmod_python.server:main"