[build]
  # Build command
  command = "cd .. && npm ci && npm run build:all && npm run docs:generate && cd docs && npm run build"
  
  # Directory to publish
  publish = "docs/dist"
  
  # Environment variables
  [build.environment]
    NODE_VERSION = "18"

# Redirects and rewrites
[[redirects]]
  # Handle client-side routing
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Role = ["admin"]}

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache static assets
[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
    
[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]  
  for = "*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000"